version: '2'

services:
  asktable_secure_tunnel:
    image: datamini/asktable-secure-tunnel:1.2
    container_name: asktable_secure_tunnel
    restart: always
    environment:
      ASKTABLE_TOKEN: admin
      SECURETUNNEL_ID: ATST_ID

